name: Build Kivy APK

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build APK
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          command: buildozer android debug

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: Kivy-APK
          path: bin/*.apk

      - name: Upload logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: Build-Logs
          path: |
            .buildozer/logs/**
            *.log
